version: "3"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "db_name"
      POSTGRES_USER: "user_name"
      POSTGRES_PASSWORD: "user_password"
    ports:
      - "5432:5432"
